language: ruby
rvm:
- 1.8.7
- ree
- 1.9.3
- 2.0
- 2.1.10
- 2.2.8
- 2.3.5
- 2.4.2
before_install:
- gem install bundler
- gem update --system
before_script:
- bundle exec appraisal install
cache: bundler
script: bundle exec appraisal rspec
