language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.3
  - 2.0
  - 2.1.2
gemfile:
  - gemfiles/rails_2.3.gemfile
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: ree
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: ree
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_2.3.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_2.3.gemfile
    - rvm: 2.1.2
      gemfile: gemfiles/rails_2.3.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_3.0.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_3.0.gemfile
    - rvm: 2.1.2
      gemfile: gemfiles/rails_3.0.gemfile
cache: bundler
before_script:
  - unset RAILS_ENV
script: bundle exec rspec
