language: ruby
rvm:
- 2.2.9
- 2.3.6
- 2.4.3
- 2.5.0
before_install:
- gem install bundler
- gem update --system
before_script:
- bundle exec appraisal install
cache: bundler
script: bundle exec appraisal rspec
